services:
  chatbot:
    container_name: chatbot
    build: .
    restart: unless-stopped
    env_file:
      - .env
      - .env.development
    working_dir: /app
    command: ["npm", "run", "start"]
    networks:
      - codr-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot.rule=Host(`chat.codrstudio.dev`)"
      - "traefik.http.routers.chatbot.entrypoints=websecure"
      - "traefik.http.routers.chatbot.tls.certresolver=letsencrypt"
      - "traefik.http.services.chatbot.loadbalancer.server.port=3000"

networks:
  codr-net:
    external: true

