services:
  embedbase:
    image: ghcr.io/different-ai/embedbase:latest
    volumes:
      - ./data:/app/embedbase_data
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.embedbase.rule=Host(`etl.codrstudio.dev`)"
      - "traefik.http.routers.embedbase.entrypoints=websecure"
      - "traefik.http.routers.embedbase.tls.certresolver=letsencrypt"
      - "traefik.http.services.embedbase.loadbalancer.server.port=8000"
networks:
  default:
    name: codr-net
    external: true