services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./data:/usr/share/nginx/html:ro
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal.rule=Host(`codrstudio.dev`)"
      - "traefik.http.routers.portal.entrypoints=websecure"
      - "traefik.http.routers.portal.tls.certresolver=letsencrypt"
      - "traefik.http.services.portal.loadbalancer.server.port=80"
networks:
  default:
    name: codr-net
    external: true