services:
  code-server:
    image: ghcr.io/coder/code-server:latest
    hostname: code-server
    container_name: code-server
    restart: unless-stopped
    volumes:
      - ./data:/home/coder
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`code.codrstudio.dev`)"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.tls.certresolver=letsencrypt"
      - "traefik.http.services.code-server.loadbalancer.server.port=8080"
    networks:
      - codr-net

networks:
  codr-net:
    external: true

