services:
  code-server:
    image: codercom/code-server:latest
    volumes:
      - ./data:/home/coder/project
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`code.codrstudio.dev`)"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.tls.certresolver=letsencrypt"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"
networks:
  default:
    name: codr-net
    external: true

