services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    restart: unless-stopped
    volumes:
      - ./data:/root/.flowise
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flowise.rule=Host(`flowise.codrstudio.dev`)"
      - "traefik.http.routers.flowise.entrypoints=websecure"
      - "traefik.http.routers.flowise.tls.certresolver=letsencrypt"
      - "traefik.http.services.flowise.loadbalancer.server.port=3000"
    networks:
      - codr-net
    command: /bin/sh -c "sleep 3; flowise start"

networks:
  codr-net:
    external: true
