---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: info
  format: text
  file_path: ""
  keep_stdout: true

totp:
  issuer: CodrStudio
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Bypass rule for Authelia itself
    - domain: auth.codrstudio.dev
      policy: bypass
    
    # Admin access to Traefik dashboard
    - domain: panel.codrstudio.dev
      policy: two_factor
      subject: "group:admins"
    
    # Default rule for all other services - require authentication
    - domain: "*.codrstudio.dev"
      policy: one_factor
      subject: "group:users"

session:
  name: authelia_session
  domain: codrstudio.dev
  same_site: lax
  secret: file:///config/data/session_secret
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  redis:
    host: redis
    port: 6379
    password: authelia_redis_pass
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: file:///config/data/storage_encryption_key
  local:
    path: /config/data/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/data/notification.txt

theme: dark

identity_providers:
  oidc:
    hmac_secret: file:///config/data/oidc_hmac_secret
    issuer_private_key: file:///config/data/oidc_private_key
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    clients:
      - id: traefik
        description: Traefik Dashboard
        secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - https://panel.codrstudio.dev/oauth2/callback
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signing_algorithm: none