services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    volumes:
      - ./configuration.yml:/config/configuration.yml:ro
      - ./users_database.yml:/config/users_database.yml:ro
      - ./notification.yml:/config/notification.yml:ro
      - ./theme:/config/theme:ro
      - authelia-data:/config/data
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/config/data/jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/config/data/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/data/storage_encryption_key
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/config/data/oidc_hmac_secret
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE=/config/data/oidc_private_key
    labels:
      - "traefik.enable=true"
      # Rota principal do Authelia
      - "traefik.http.routers.authelia.rule=Host(`auth.codrstudio.dev`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
      - "traefik.http.routers.authelia.service=authelia"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      
      # Middleware de autenticação para outros serviços
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.codrstudio.dev"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      
      # Middleware adicional para bypass em endpoints específicos
      - "traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify"
      - "traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
    networks:
      - codr-net
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: authelia-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-authelia_redis_pass}
    volumes:
      - redis-data:/data
    networks:
      - codr-net
    labels:
      - "traefik.enable=false"

volumes:
  authelia-data:
    driver: local
  redis-data:
    driver: local

networks:
  codr-net:
    external: true