alias ll="ls -lha"
alias ?="grep"
alias install="apt install"
alias i="apt install"
alias remove="apt remove"
alias purge="apt purge"
alias update="apt update"
alias search="apt-cache search"
alias serach="apt-cache search"
alias s="apt-cache search"

alias unstage="git restore --staged"
alias ci="git commit"
alias st="git status"
alias add="git add -f"
alias push="git push"
alias pull="git pull"
alias revert="git restore"
alias revert-all="git restore ."
alias restore="git restore"
alias restore-all="git restore ."

alias up="docker compose up -d"
alias down="docker compose down"
